In [1]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 38A6-1C25

 Directory of C:\Users\Administrator\Documents\data science

02-03-2023  00:09    <DIR>          .
23-02-2023  17:15    <DIR>          ..
01-03-2023  22:14    <DIR>          .ipynb_checkpoints
26-02-2023  19:40             4,295 assignments.ipynb
06-02-2023  19:59           103,983 BEML.csv
23-02-2023  10:21             3,527 Cars.csv
01-03-2023  22:12            29,822 claimants.csv
28-02-2023  20:39            31,805 core python class.ipynb
06-02-2023  19:59           107,633 GLAXO.csv
30-01-2023  09:40             3,858 iris.csv
23-02-2023  10:29           136,976 machine learning class 2.ipynb
27-02-2023  23:11           730,568 Multi Linear Regression-updated .ipynb
22-02-2023  21:20           122,846 practice.ipynb
20-02-2023  14:46           346,129 python datascience class 1.ipynb
02-03-2023  00:09            37,867 Untitled.ipynb
17-02-2023  10:30             1,172 wc-at.csv
              13 File(s)      1,660,4

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [2]:
data=pd.read_csv("claimants.csv")

In [3]:
data

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [6]:
data.nunique()
#np.unique(data["CASENUM"])

ATTORNEY      2
CLMSEX        2
CLMINSUR      2
SEATBELT      2
CLMAGE       68
LOSS        916
dtype: int64

In [5]:
del data["CASENUM"]

In [19]:
data.head()

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0         0     0.0       1.0       0.0    50.0  34.940
1         1     1.0       0.0       0.0    18.0   0.891
2         1     0.0       1.0       0.0     5.0   0.330
3         0     0.0       1.0       1.0    31.0   0.037
4         1     0.0       1.0       0.0    30.0   0.038

In [8]:
data.isna().sum()    #null values in each column

ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [9]:
data=data.dropna()

In [10]:
data.isna().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [11]:
model=LogisticRegression()
features=data.iloc[:,1:]
target=data["ATTORNEY"]
model.fit(features,target)

# if we wants to select middle variable as targetthen
# data[[col for col in data.columns if col!="sepal_width"]]

LogisticRegression()

In [12]:
pred=model.predict(features)

In [13]:
print(classification_report(target,pred))
# checking the performance

              precision    recall  f1-score   support

           0       0.76      0.66      0.70       578
           1       0.67      0.76      0.71       518

    accuracy                           0.71      1096
   macro avg       0.71      0.71      0.71      1096
weighted avg       0.71      0.71      0.71      1096



In [14]:
model.coef_          # there are 5 features so m1,m2,m3,m4,m5

array([[ 0.42687928,  0.57068784, -0.59439873,  0.00653888, -0.38424791]])

In [15]:
model.intercept_

array([-0.17361679])

# iris

In [26]:
data=sns.load_dataset("iris")

In [27]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [1]:
data["sepal width"]
data[[col for col in data.columns if col != "sepal width"]] # we can use this when feature is in the middle

NameError: name 'data' is not defined

In [28]:
 """
 data-->train and test
 
 train--> create
 
 test-->evaluate
 
 """

'\ndata-->train and test\n\ntrain--> create\n\ntest-->evaluate\n\n'

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(
    data.iloc[:,:-1],data.iloc[:,-1],test_size=0.2)

#we are separating the data into two parts training data and testing data 
# x_train and x_test are features, and y_train and y_test are target 
# 50% of data will be divided form training and 50% for test
# model evaluation process is completely based on test data if perform is good it is good model

In [31]:
x_train

sepal_length  sepal_width  petal_length  petal_width
124           6.7          3.3           5.7          2.1
27            5.2          3.5           1.5          0.2
96            5.7          2.9           4.2          1.3
50            7.0          3.2           4.7          1.4
32            5.2          4.1           1.5          0.1
..            ...          ...           ...          ...
148           6.2          3.4           5.4          2.3
12            4.8          3.0           1.4          0.1
121           5.6          2.8           4.9          2.0
62            6.0          2.2           4.0          1.0
78            6.0          2.9           4.5          1.5

[120 rows x 4 columns]

In [32]:
x_test

sepal_length  sepal_width  petal_length  petal_width
109           7.2          3.6           6.1          2.5
13            4.3          3.0           1.1          0.1
83            6.0          2.7           5.1          1.6
21            5.1          3.7           1.5          0.4
88            5.6          3.0           4.1          1.3
117           7.7          3.8           6.7          2.2
139           6.9          3.1           5.4          2.1
122           7.7          2.8           6.7          2.0
58            6.6          2.9           4.6          1.3
118           7.7          2.6           6.9          2.3
84            5.4          3.0           4.5          1.5
66            5.6          3.0           4.5          1.5
30            4.8          3.1           1.6          0.2
128           6.4          2.8           5.6          2.1
120           6.9          3.2           5.7          2.3
31            5.4          3.4           1.5          0.4
4             5.0          3.6           1.4          0.2
132           6.4          2.8           5.6          2.2
54            6.5          2.8           4.6          1.5
149           5.9          3.0           5.1          1.8
86            6.7          3.1           4.7          1.5
97            6.2          2.9           4.3          1.3
10            5.4          3.7           1.5          0.2
80            5.5          2.4           3.8          1.1
2             4.7          3.2           1.3          0.2
111           6.4          2.7           5.3          1.9
43            5.0          3.5           1.6          0.6
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
37            4.9          3.6           1.4          0.1

In [33]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

# parameters analysis

In [34]:
model.coef_

array([[-0.39618211,  0.94856676, -2.39872009, -1.04189949],
       [ 0.54503553, -0.30004379, -0.22118874, -0.78574584],
       [-0.14885342, -0.64852297,  2.61990883,  1.82764533]])

In [35]:
model.intercept_

array([  9.18241078,   1.83810333, -11.02051412])

# evaluation

In [36]:
pred=model.predict(x_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



# correlation

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"c1":[10,5,9,1],"c2":[2,4,3,7]})

In [3]:
data.corr()

c1        c2
c1  1.000000 -0.975419
c2 -0.975419  1.000000